name: Rust

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 6,10,14,16,22 * * *'
  watch:
    types: started
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    - name: Build
      run: cargo build
#     - name: Run tests
#       run: cargo test --verbose
    - name: Run
      run: |
        cargo run --package step_up --bin step_up ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }} ${{ secrets.STEPS }}
