name: Rust

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 6,10,14,16,22 * * *'
  watch:
    types: started
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: debug
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set time zone
      run: export TZ='Asia/Shanghai'
    - name: Build
      run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
    - name: Run
      run: |
        account =${{ secrets.ACCOUNT }}
        password = ${{ secrets.PASSWORD }}
        steps = ${{ secrets.STEPS }}
        cargo run --package step_up --bin step_up "$account" "$password" "$steps"
